### ISSUE TITLE
Is there an API for testing a feed?

### ISSUE THREAD

**Issue by scripting** [w3c/feedvalidator#110]
Is there an API for your feed validator? 

I'd like to submit my feed to it periodically to keep track of changes. 

A very simple API will do. I send you the url of a feed, you send me back the results of validation in a JSON object.

**Comment by Lucidiot** [comment]
[There is one](https://validator.w3.org/feed/docs/soap.html) with an SOAP response: https://validator.w3.org/feed/check.cgi?output=soap12&url=https://www.rssboard.org/files/sample-rss-2.xml
