### ISSUE TITLE
https://validator.w3.org/feed/ 503 Service Unavailable

### ISSUE THREAD

**Issue by michaelschofield** [w3c/feedvalidator#121]
**Describe the bug**
[A clear and concise description of what the bug is.](https://validator.w3.org/feed/) shows a 503. 

**To Reproduce**
URL that triggered the bug: https://validator.w3.org/feed/

**Expected behavior**
I just want to make sure someone knows it's down, if anyone's paying attention. It's been down for a couple of days.

**Comment by dontcallmedom** [comment]
thanks for the ping - it is back up now
