### ISSUE TITLE
Q: are you consuming changes of forked project?

### ISSUE THREAD

**Issue by joachimlindenberg** [w3c/feedvalidator#124]
according to the about this is forked from https://github.com/rubys/feedvalidator/. Are you merging changes of that project?
Which project would you recommend to host oneself?

**Comment by dontcallmedom** [comment]
This fork has been upgraded to python3, when the original project hasn't.

There is no automated tracking from changes made upstream, which in general may no longer easily apply given the change of based python version. AFAICT, the recent changes brought upstream were import from changes made in this fork.

Given that python2 is no longer supported, I would also say this fork is probably a better recommendation, but YMMV :)
