### ISSUE TITLE
Feed validator fails on HTML comments in <content:encoded>

### ISSUE THREAD

**Issue by hannob** [w3c/feedvalidator#13]
I noticed the feed validator code fails on RSS feeds with (correctly encoded) HTML comments in the <content:encoded> part. I believe this is a bug in the validator, as I don't see a reason why there shouldn't be HTML comments within that part. The web frontend gives no helpful indication to the user what might be wrong.

A minimal example would look like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title>example</title>
<link>https://example.org/</link>
<description>example</description>
<item>
<title>example</title>
<content:encoded>
&lt;!-- test --&gt;
</content:encoded>
</item>
</channel>
</rss>
```

This causes an Attribute error in the python code (will attach error message).
[feedvalidator-local-error.txt](https://github.com/w3c/feedvalidator/files/4563255/feedvalidator-local-error.txt)

This will make the validator fail on most feeds of the serendipity blog software, which commonly uses HTML comments, see also https://github.com/s9y/Serendipity/issues/713

**Comment by mont1985** [comment]
>  #``<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title>example</title>
<link>https://example.org/</link>
<description>example</description>
<item>
<title>example</title>
<content:encoded>
&lt;!-- test --&gt;
</content:encoded>
</item>
</channel>
</rss>
