### ISSUE TITLE
A valid feed comes back with an error in the validation checker

### ISSUE THREAD

**Issue by milligandw** [w3c/feedvalidator#131]
Go here: https://validator.w3.org/feed/check.cgi

Enter Feed: http://rescuefirecompany.org/apps/public/news/rss

Result: Server returned HTTP Error 400: Bad Request

Enter feed URL in Chrome browser and the feed comes back as valid.

**Comment by dontcallmedom** [comment]
it may have been temporary hiccup, it returns "valid rss feed" now
