### ISSUE TITLE
RSS feed from Science Buddies ORG is not validated

### ISSUE THREAD

**Issue by larieu** [w3c/feedvalidator#137]
**Describe the bug**
apparently good rss feed not validated

**To Reproduce**
URL that triggered the bug:
https://sciencebuddies.org/blog/rss.xml

**Expected behavior**
validation

**Comment by dontcallmedom** [comment]
assuming this is about the 405 error the validator returns, this comes from the sciencebuddies.org server returns that error to the feedvalitor user agent - the validator can't validate the feed if the server refuses to send the content.
