### ISSUE TITLE
Cant Read Feed?

### ISSUE THREAD

**Issue by jobriant11** [w3c/feedvalidator#23]
https://xml.hire.ly/feed/1i37GEjlJ_UacmnoqjgpNdwkwnx-IM0ryNlz7Edpffew.xml

**Comment by dontcallmedom** [comment]
It looks like that server is not configured properly for TLS - while I can load that URL in a browser, it e.g. fails with curl:
```
 curl "https://xml.hire.ly/feed/1i37GEjlJ_UacmnoqjgpNdwkwnx-IM0ryNlz7Edpffew.xml"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

openssl reports an error: `Verification error: unable to verify the first certificate`

My guess based on [SSLLabs results](https://www.ssllabs.com/ssltest/analyze.html?d=xml.hire.ly) is that the server is missing the intermediary certificate, but I'm not at all an SSL expert.

In any case, my current assumption is that this is not a bug with the feedvalidator, but with the server the RSS feed is hosted on; please let me know if you find evidence to the contrary.

**Comment by dontcallmedom** [comment]
(in fact, it only worked in my browser because it already had cached the intermediate certificate - it fails in a fresh browser profile)
