### ISSUE TITLE
Make SSL Error messages more helpful

### ISSUE THREAD

**Issue by gdsotirov** [w3c/feedvalidator#30]
Trying to validate a feed I'm getting the following error:

`Server returned [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)`

What is the actual reason for this error?

For the problematic site I'm using a wildcard SSL certificate issued by Sectigo Limited. Checking my certificate with [SSL Server Test](https://www.ssllabs.com/ssltest/) I see "Incomplete" warning in "Chain issues". In "Certification Paths" I see that there is "Extra download" warning for the intermediate certificate. Is this what makes the validator return such error? And if so, could this error be made more meaningful?

**Comment by dontcallmedom** [comment]
Yes, that's very likely the source of the error - see https://github.com/w3c/feedvalidator/issues/23#issuecomment-664858655 

I agree the error message could be more helpful - will look into this

**Comment by gdsotirov** [comment]
Just to confirm that this was actually the problem. Some months ago I changed my site's SSL certificate from _Let's Encrypt_ to _Sectigo_, but apparently forgot to change the certificate chain file in Apache configuration:

```diff
- SSLCertificateChainFile "/etc/ssl/certs/lets_encrypt-ca.crt"
+ SSLCertificateChainFile "/etc/ssl/certs/sectigo-ca.crt"
```

Now feed validator works OK as before, but I would really appreciate a more meaningful message, because it would have saved me some time.
