### ISSUE TITLE
https://blog.salonydenon.pl/feed/gn

### ISSUE THREAD

**Issue by kwiatkowski86** [w3c/feedvalidator#31]
Hi,
please check our problem, our feed exist and works well:
https://blog.salonydenon.pl/feed/gn

but validator:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.salonydenon.pl%2Ffeed%2Fgn
shows that error:
('The read operation timed out',) (SSLError; misconfigured server?)

can You please check why?

**Comment by dontcallmedom** [comment]
The feedvalidator is configured to timeout its requests after 10s - for some reason, your server takes ~19s to respond to the requests on the feed.

**Comment by kwiatkowski86** [comment]
we have big feed, thats why it takes -19s,
all feeds that respond time is longer than 10s will show that error?

**Comment by dontcallmedom** [comment]
indeed - independently of the validator, other feed consumers may timeout with such a long wait. It may be beneficial to consider some sort of caching to reduce that time (which I assume is spent generating the content)

**Comment by kwiatkowski86** [comment]
ok, thanks for Your time.
