### ISSUE TITLE
Cannot 

### ISSUE THREAD

**Issue by orthomax2020** [w3c/feedvalidator#32]
Hi, I can't seem to validate any rss feeds from my website 
https://www.londonspine.com
Hosting company is siteground who say that there is no problem with server. All permissions have been reset and cache cleared.
Can you help ?

**Comment by dontcallmedom** [comment]
it looks like the site is protected by CloudFlare WebApp Firewall, which is blocking access from the feedvalidator - this doesn't look like an issue with the feed validator itself, so closing the issue.
