### ISSUE TITLE
w3C feedvalidator 

### ISSUE THREAD

**Issue by Edditul** [w3c/feedvalidator#34]
https://rssfeeds.aph.gov.au/senate/new_inquiries.xml

w3c feed validator returns error for the above rss link, why?

**Comment by dontcallmedom** [comment]
assuming you mean the errors about `<skipDays>` and `<skipHours>`, these elements needs sub-elements (resp `<hour>` and `<day>` - see https://www.rssboard.org/skip-hours-days
