### ISSUE TITLE
What could be the problem with this feed?

### ISSUE THREAD

**Issue by Nimrod891** [w3c/feedvalidator#35]
The link here:
https://www.cs.bgu.ac.il/~spl211/Announcements?action=rss

It used to work via blogtrottr and I stopped receiving new entries.
tuple index out of range (IndexError; misconfigured server?)

**Comment by dontcallmedom** [comment]
The underlying server (cs.bgu.ac.il) is not responding to HTTP requests - from a cursory investigation, it seems to have moved to https://in.bgu.ac.il/~spl211/ (which itself reports a 500 error).

From the feedvalidator perspective, the server timeouts, which the error message didn't make clear -  I have improved the error message in #36
