### ISSUE TITLE
Feed doesn't validate but is visible?

### ISSUE THREAD

**Issue by Cpointcc** [w3c/feedvalidator#37]
https://cpointcc.com/rss/cpcc-feeds

Can someone explain this?  I can see the feed data, but it is not validating?  SSL Issue?  Is this a cloudflare incompatibility?

('The read operation timed out',) (SSLError; misconfigured server?) [help]

Sorry
An error occurred while trying to validate this feed.

Possible causes:

The address may be incorrect. Make sure the address is spelled correctly. Try loading the feed directly in your browser to make sure a feed exists at that address.
The feed may be temporarily unavailable. The server may be down, or too slow. Try again later.
The validator may be busted. If the feed exists, the server is fine, and the problem is reproducible, please raise an issue.

**Comment by dontcallmedom** [comment]
yes, this is due to the Cloudflare Firewall for WebApps blocking access from the feedvalidator.

**Comment by Cpointcc** [comment]
Can you direct me to some resolution?

**Comment by dontcallmedom** [comment]
as a short term solution, you could paste the content of the feed into "Direct input" mechanism https://validator.w3.org/feed/#validate_by_input

For a more robust solution, I think you would have to configure the Firewall to put the feedvalidator on some kind of allow-list, but I don't have enough experience with that system to guide more specific guidance.

**Comment by Cpointcc** [comment]
Thank you!

Sue
[cid:image001.jpg@01D6F3C4.CF95AA00]

Sue Grady
IT Specialist/Web Developer
1622 4th Street
Peru, IL  61354
P:  815-223-1052
F:  815-223-0791
E:  sgrady@cpointcc.com<mailto:sgrady@cpointcc.com>
