### ISSUE TITLE
Debugging Docker-based installs

### ISSUE THREAD

**Issue by juliend2** [w3c/feedvalidator#39]
![image](https://user-images.githubusercontent.com/30395/111858060-55fa1e00-890c-11eb-81ea-104eaff76652.png)

> Possible causes:
> 
> The address may be incorrect. Make sure the address is spelled correctly. Try loading the feed directly in your browser to make sure a feed exists at that address.
> The feed may be temporarily unavailable. The server may be down, or too slow. Try again later.
> The validator may be busted. If the feed exists, the server is fine, and the problem is reproducible, please raise an issue.

I also tried with http://waitbutwhy.com/feed and it is the same problem.

I did exactly what was told in the readme for running on docker.

I'm using Docker for Windows.
Here are my configs:

![image](https://user-images.githubusercontent.com/30395/111858104-acfff300-890c-11eb-84fe-7c6ea4a52d27.png)

But when I try on https://validator.w3.org/feed/ , it works for both.
Just locally by using docker, it doesn't work.

**Comment by dontcallmedom** [comment]
can you find the logs? there should be more details about the underlying error

**Comment by juliend2** [comment]
@dontcallmedom I try to see, even with `docker logs -f <container_id>`, but I see nothing, when I run the container.

I do `docker run -p 8080:80 feedvalidator` inside a WSL console.

How do you get those logs when running it ?

**Comment by ahpetrot** [comment]
Running into the same issue.  Appears that no docker logs are generated at container start up.  ( Docker Windows ) .    Web UI comes up for all feed validation checks fail to "Sorry".. My instances is also coming back "Service Unavailable. 

In the container the /var/log/apache2/error.log shows the following:

[Tue Jun 15 14:02:18.429493 2021] [cgid:error] [pid 11:tid 140620786038528] (2)No such file or directory: [client 172.17.0.1:47944] AH02833: ScriptSock /var/run/apache2/cgisock.8 does not exist: /feedvalidator/check.cgi
[Tue Jun 15 14:02:27.133990 2021] [cgid:error] [pid 11:tid 140620777645824] (2)No such file or directory: [client 172.17.0.1:47954] AH02833: ScriptSock /var/run/apache2/cgisock.8 does not exist: /feedvalidator/check.cgi, referer: http://localhost:8090/
[Tue Jun 15 14:03:48.500954 2021] [cgid:error] [pid 10:tid 140620634969856] (2)No such file or directory: [client 172.17.0.1:48002] AH02833: ScriptSock /var/run/apache2/cgisock.8 does not exist: /feedvalidator/check.cgi, referer: http://localhost:8090/
[Tue Jun 15 14:04:15.172737 2021] [cgid:error] [pid 10:tid 140620702111488] (2)No such file or directory: [client 172.17.0.1:48028] AH02833: ScriptSock /var/run/apache2/cgisock.8 does not exist: /feedvalidator/check.cgi, referer: http://127.0.0.1:8090/
[Tue Jun 15 14:04:41.550896 2021] [cgid:error] [pid 10:tid 140620718896896] (2)No such file or directory: [client 172.17.0.1:48042] AH02833: ScriptSock /var/run/apache2/cgisock.8 does not exist: /feedvalidator/check.cgi, referer: http://127.0.0.1:8090/

**Comment by ahpetrot** [comment]
Just validated this running on linux instances and having the same issues as above, no docker logging and Service Unavailable.

**Comment by dontcallmedom** [comment]
@josephw since you contributed the initial Docker configuration, would you be amenable to taking a look into this?

**Comment by danielfdickinson** [comment]
The following diff combined with `--net="host"` is sufficient for me, using docker from Ubuntu 22.04 in a multipass instance on Windows 11:

```patch
diff --git a/Dockerfile b/Dockerfile
index 45295159..a1bcf896 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,8 +1,8 @@
-FROM debian:9.6
+FROM debian:12
 
 RUN apt-get update
 RUN apt-get --yes install apache2
-RUN apt-get --yes install python
+RUN apt-get --yes install python3 python3-libxml2 python3-rdflib python3-rdflib-jsonld
 RUN apt-get --yes install ca-certificates
 
 RUN a2dissite 000-default
```

Note that applying this breaks `time.cgi` and `status.cgi` as they depend on python2 which is no longer available in new Debian releases.

The docker command I used was `docker run -d --net="host" feedvalidator:latest` inside a VSCode terminal (which made forwarding port 80 to the host easy).

I can push the diff above as a PR, along with fixes for `time.cgi` and `status.cgi` if wished (@dontcallmedom).
