### ISSUE TITLE
Error when fetching content over HTTPs

### ISSUE THREAD

**Issue by chromeo** [w3c/feedvalidator#40]
When checking the feed "https://reidrealestate.com/feed/xml" I get this error message:
Error when fetching content over HTTPs: "HTTPs server has incorrect certificate configuration"

I inspected the source using Chrome Inspector, all appears to be in order with the certificate. Is it possible the opening tag is misconfigured instead of being an https issue?
![Screen Shot 2021-04-06 at 8 23 15 AM](https://user-images.githubusercontent.com/1266796/113735745-64d52480-96b1-11eb-9f8b-64b3471367f6.png)

**Comment by dontcallmedom** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=reidrealestate.com shows the certificate chain is incomplete, which explains why the feed validator complains about the SSL configuration.

(I believe Chrome using a blank profile would complain as well)
