### ISSUE TITLE
IncompleteRead(0 bytes read), but feed exists.

### ISSUE THREAD

**Issue by nitz** [w3c/feedvalidator#41]
Hello!

I'm receiving this error when trying to validate [this](https://cmd.wtf/scripts/adafruit_new_fixed.php) feed.

`IncompleteRead(0 bytes read) (IncompleteRead; misconfigured server?)`

The feed is visible via my web browser, and via curl, and several other web API apps I've used. The logs on my server are showing the whole access like it should, but the validator is dying out before it receives any bytes it seems?

Any ideas?

Thanks!

P.S.: The script does take a few hundred ms to run, as it is actually pulling a feed from [this url](https://www.adafruit.com/feed/contextly_new.xml) internally, and attempting to fix the RSS XML before re-rendering it and passing it on. I can't tell if that has anything to do with anything! 🤷🏻‍♀️

**Comment by dontcallmedom** [comment]
I confirm there is a problem, although it seems to be with the server side on your end, when requesting content with HTTP/1.1 (vs 2 which curl uses by default).

You can reproduce the issue with curl with:
```
$ curl --http1.1  https://cmd.wtf/scripts/adafruit_new_fixed.php
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```

**Comment by nitz** [comment]
Dominique:

Fantastic find. Sure enough every single other tool I tried was defaulting (I suppose perhaps is a good thing) to HTTP 2! Turns out your one simple curl call there helped me find a _long_ standing misconfiguration on my server where many requests were getting tagged with `Transfer-Encoding: chunked`, despite not actually being.

I greatly appreciate your time and wonderful response!
