### ISSUE TITLE
Receiving 403 Forbidden error when trying to validate RSS Feed

### ISSUE THREAD

**Issue by bsudhir6** [w3c/feedvalidator#48]
Hi I am receiving 403 forbidden error when trying validate feed please help.

Feed URL: https://fitgirl-repacks.site/feed/

this url opens just fine but when tried to validate on your system it is failing.

**Comment by dontcallmedom** [comment]
The feed validator is blocked by DDOS-GUARD by which the said URL seems to be protected.
