### ISSUE TITLE
iTunes categories out of date

### ISSUE THREAD

**Issue by drewknab** [w3c/feedvalidator#5]
[Current iTunes Podcast Categories](https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12?utm_source=podnews.net&utm_medium=web&utm_campaign=podnews.net:2019-06-05)

[ iTunes Podcast Categories in this repo](https://github.com/w3c/feedvalidator/blob/master/src/feedvalidator/itunes.py)

Looks like the categories flipped over last August.

**Comment by dontcallmedom** [comment]
closed in #6 - thanks!
