### ISSUE TITLE
Server returned HTTP Error 500

### ISSUE THREAD

**Issue by Obaidshah** [w3c/feedvalidator#50]
Hi, the is showing Server returned HTTP Error 500: Internal Server Error.  The feed is working properly. Can you please see what could be the problem with the link https://bit.ly/3yExoAK

**Comment by dontcallmedom** [comment]
that feeds returns a 500 error page "Worker threw exception" (with a page generated by CloudFlare inviting the site owner to check the error log there) when fetched from a non-browser context.
