### ISSUE TITLE
Server returned [Errno 99] Cannot assign requested address but I can open the file in my webbrowser

### ISSUE THREAD

**Issue by JamesRead5737** [w3c/feedvalidator#57]
When using the rss feed validator ​http://validator.w3.org/feed/ I get the error "Server returned [Errno 99] Cannot assign requested address". This doesn't make sense to me because I am able to open the xml file in my web browser (Chrome).

**Comment by dontcallmedom** [comment]
can you say  what URL you were validating when getting this error? it won't be possible to debug it otherwise

**Comment by JamesRead5737** [comment]
http://www.wottot.com/rss.xml

**Comment by JamesRead5737** [comment]
I just put a copy of RT's news feed on my server https://www.rt.com/rss/news/ and I get the same error while validating directly from the RT website works just fine. So whatever the problem is I think it's with my server.

**Comment by dontcallmedom** [comment]
it looks like the feed validator may not not configured properly to access IPv6 only servers - investigating this further

**Comment by dontcallmedom** [comment]
this was indeed the problem, and it has now been fixed, many thanks for the report!
