### ISSUE TITLE
Error when fetching content over HTTPs: "HTTPs server has incorrect certificate configuration" 

### ISSUE THREAD

**Issue by JamesRead5737** [w3c/feedvalidator#60]
I get the following error when using the validator:

Error when fetching content over HTTPs: "HTTPs server has incorrect certificate configuration" 

I don't understand why I get this error. I can access the URL with my browser (Chrome). 
https://www.wottot.com/rss.rss

**Comment by dontcallmedom** [comment]
the [linked help message](https://validator.w3.org/feed/docs/error/HttpsProtocolError.html) states:
> most likely, the server is not configured with the full chain of intermediate certificates.

and indeed, an SSL report such as [SSLLabs'](https://www.ssllabs.com/ssltest/analyze.html?d=www.wottot.com&s=2001%3a41d0%3a800%3a2654%3a0%3a0%3a0%3a0) reports an incomplete certificate chain.

It works in browsers that have already interacted with the intermediary certificate, but it wouldn't work with a blank profile.
