### ISSUE TITLE
I need help with this feed

### ISSUE THREAD

**Issue by agdoraly** [w3c/feedvalidator#69]
Hello! We try to connect our feed with GetResponse which use https://validator.w3.org/feed/ . Even our feed works with Google, when we try to valide in your system we receive the following message and we dont understand why?

"The read operation timed out (Server timed out; misconfigured server?)"

Can you help us please?

Our link feed is: https://doraly.ro/api/v1/product/productsJson/googleFeed

**Comment by dontcallmedom** [comment]
the feedvalidator is configured to timeout after 10s and limited to download 5MB of data; it takes around 20s to download the above feed, which also weights 26.5MB, so the feedvalidator won't be able to validate it at the moment.
