### ISSUE TITLE
Costar RSS Feed down?

### ISSUE THREAD

**Issue by leonardramirezjr** [w3c/feedvalidator#72]
Attempted to add the RSS feed for CoStar Commercial Real Estate News on the LearnWorlds platform.

Attempted to validate the Costar RSS feed and received his error:

CoStar Commercial Real Estate News
There was an error while running the web page.
This error may have be caused because of a database error, or because our website is experiencing temporary problems.

Using the wc3/feedvalidator.

**Comment by dontcallmedom** [comment]
do you have a link to the rss feed in question?

**Comment by leonardramirezjr** [comment]
Lol after looking at your id, I wrote Hi Dom, then realized what your ID said. It's going to be one of those days.

I asked my colleague because I couldn't find it in my email. She said she thought this was it:
https://www.costar.com/?gclid=Cj0KCQiAuvOPBhDXARIsAKzLQ8Ex_VD0gPFxeHK8YIv5VVNnzlyMyrsH12s5mhoWSndpLErCw6PYoXYaAm03EALw_wcB

**Comment by leonardramirezjr** [comment]
Here's the url I picked the url up from:
http://www.erealtynj.com/default.asp.f-rss
It's the second one listed. If you click on it, you'll see the errors.

**Comment by dontcallmedom** [comment]
it looks like the problem lies entirely with the Costar Web site, and is not related to the feedvalidator itself, so I'll be closing this issue.

(as an aside, it's absolutely appropriate to call me Dom; my nickname is an obscure joke)

**Comment by leonardramirezjr** [comment]
Lol  Thanks for the heads up Dom. I'll notify Costar.

Len
