### ISSUE TITLE
Problem validating a RSS feed

### ISSUE THREAD

**Issue by colincoo** [w3c/feedvalidator#76]
**Describe the bug**
A RSS feed put out by the American Psychological Association doesn't validate

**To Reproduce**
[URL that triggered the bug:](https://content.apa.org/journals/psp.rss)

**Expected behavior**
Feed to validate correctly

**Additional context**

**Comment by dontcallmedom** [comment]
The bogus error message is now fixed; the underlying problem is that the feedvalidator is receiving a "403 forbidden" response when fetching the RSS feed, apparently due to "Incapsula" forbidding access to the feed.
