### ISSUE TITLE
Trying to Validate an RSS Feed for my Podcast

### ISSUE THREAD

**Issue by Waltonm11** [w3c/feedvalidator#80]
The Bug

The bug in question, occurred when I tried to validate a URL for my Podcast from Libsyn. 

When I entered the feed URL and pressed enter, the page flashed up showing that I hadn't edited the 'Explicit Lyrics' section, and that it should read 'yes', 'no' or 'clean'. 

The issue is that this is confirmed done on Libsyn, which leaves me somewhat stumped :F 

Am I missing something? 

All the best,

Monty 

The URL

https://feeds.libsyn.com/350945/rss

What I expected to happen

Thank you for Validating your podacast with us! Celebrations and Ewoks a-plenty

**Comment by Marzal** [comment]
The URL for the feed doesn't work anymore.
