### ISSUE TITLE
Add the schema.org namespace to the list of recognized namespaces

### ISSUE THREAD

**Issue by acabal** [w3c/feedvalidator#84]
We're trying to validate OPDS feeds, which are a superset of Atom 1.0 feeds.

As part of that, we would like to use elements in the schema.org namespace, for example including `<schema:alternateName>` as a child of `<author>`. But, the validator doesn't recognize `xmlns:schema="http://schema.org/"` (or `xmlns:schema="https://schema.org/"`, note the https) as a valid namespace.

Schema.org is a very popular namespace used all over the web and publishing industry. I suggest adding it to the list of namespaces recognized  by the validator.

**Comment by dontcallmedom** [comment]
can you provide a sample of such feed to help with testing for that change?

**Comment by dontcallmedom** [comment]
thanks for the sample! looking at it, the validator consider the said sample valid, with just a warning about the namespace being unknown. I could easily made the validator give a warning that it would not validate content under that namespace, but I'm not sure how much of an improvement that would be.

Actually validating schema.org content would naturally be much more involved.

Could you clarify what you would expect the validator to do with content in that namespace?

**Comment by acabal** [comment]
In the [error message explanation](https://validator.w3.org/feed/docs/warning/UnknownNamespace.html), it says that the validator recognizes a large number of namespaces as valid. I don't think we need to *validate* elements in the schema.org namespace - the namespace is huge and changing - merely to recognize that it's a popular namespace, and that its presence shouldn't generate a warning.

In other words I don't know if "supporting a namespace" in the validator means "we validate that namespace's schema as part of the feed validation" or if it means "we acknowledge the namespace exists and won't raise warnings/errors about it". I was expecting the latter.

(Though, maybe actually validating schema.org may be a good long term goal, as at least in the non-feed world it's becoming the de facto general microdata schema.)
