### ISSUE TITLE
Feed Validation

### ISSUE THREAD

**Issue by lapillococonuts** [w3c/feedvalidator#89]
**Describe the bug**
I tried to validate some feed for Google News but an error occurred. The feeds on my site www.destinazioneavventura.it seems to be ok.

**To Reproduce**
https://www.destinazioneavventura.it/mare/feed/

**Expected behavior**

**Additional context**

**Comment by dontcallmedom** [comment]
can't see any error in https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.destinazioneavventura.it%2Fmare%2Ffeed%2F - closing this issue, but please re-open it if there is something I'm missing
