### ISSUE TITLE
Specific Feed Validates when pasted in, but not when using the URI

### ISSUE THREAD

**Issue by wkeving** [w3c/feedvalidator#90]
**Describe the bug**
The feed at https://roaddirt.tv/feed/ is not validating via URI, returning a 503 error, but it will validate when pasting in the feed data in Direct Input.

**To Reproduce**
URL that triggered the bug: https://roaddirt.tv/feed/

**Expected behavior**
If the feed data validates on Direct Input, I would expect it to validate using URI.

**Additional context**
Discovered when Mailchimp reported the feed as invalid according to w3c validator.

**Comment by dontcallmedom** [comment]
I can't seem to be able to reproduce this at the moment - maybe this was a temporary network or server issue? Please re-open if you're still seeing this.

**Comment by wkeving** [comment]
It was legit. Server files/folders permissions had gotten out of whack.
Resetting them corrected the issue. Thanks.
