### ISSUE TITLE
https://www.infojobs.net/trabajos.rss/kw_ssis/ is parsed as invalid

### ISSUE THREAD

**Issue by rventuradiaz** [w3c/feedvalidator#92]
feedvalidator is parsing several feeds from domain www.infojobs.net as invalid.
https://www.infojobs.net/trabajos.rss/kw_ssis/
I checked in Firefox browser and the url is valid, and retrieving results.
Would you please check this use case?
Thanks and best regards,

**Comment by dontcallmedom** [comment]
as far as I can determine, the validator is blocked from accessing [www.infojobs.net](http://www.infojobs.net/) by cloudfront (it's getting a 405 error); this sounds like something that would have to be unblock on your side.
