### ISSUE TITLE
Feed is displaying in browser

### ISSUE THREAD

**Issue by socialpilgrim** [w3c/feedvalidator#99]
**Describe the bug**
Feed is displaying in browser but not validating , getting error "An error occurred while trying to validate this feed."

**To Reproduce**
https://policykeys.com/feed

**Expected behavior**
Url feed should be validated and show congratulations messages

**Additional context**
Showing error message 
"Sorry
An error occurred while trying to validate this feed."

**Comment by rcaden** [comment]
When I try to load that feed, instead of the feed I see an error page "ErrorException: Attempt to read property 'name' on null" linked to a line of code that references "{{Auth::user()->name}}".

**Comment by dontcallmedom** [comment]
problem is in the feed generation, not the validator
